(()=>{
        const initialApplications=[
            {id:'BUR-2026-0148',name:'Amara Okafor',email:'amara.okafor@campus.edu',course:'BSc Environmental Science',year:'Year 2',type:'Need-based bursary',amount:2400,status:'Under review',date:'18 Sep 2026',initials:'AO',note:'My family income changed this year after my parent lost their job. This support would help cover tuition and transport.'},
            {id:'BUR-2026-0147',name:'Ethan Williams',email:'ethan.williams@campus.edu',course:'BA Public Policy',year:'Year 3',type:'Merit bursary',amount:1800,status:'Submitted',date:'17 Sep 2026',initials:'EW',note:'I have maintained a strong academic record while volunteering in community tutoring.'},
            {id:'BUR-2026-0146',name:'Priya Nair',email:'priya.nair@campus.edu',course:'BEng Computer Science',year:'Year 1',type:'Access bursary',amount:3200,status:'Needs information',date:'16 Sep 2026',initials:'PN',note:'I am the first in my family to attend university and need assistance with essential study equipment.'},
            {id:'BUR-2026-0145',name:'Noah Mensah',email:'noah.mensah@campus.edu',course:'BSc Nursing',year:'Year 2',type:'Need-based bursary',amount:2100,status:'Approved',date:'14 Sep 2026',initials:'NM',note:'Support with travel costs for clinical placements would make it possible for me to continue my course.'},
            {id:'BUR-2026-0144',name:'Sofia Garcia',email:'sofia.garcia@campus.edu',course:'BA Architecture',year:'Year 4',type:'Merit bursary',amount:1500,status:'Submitted',date:'12 Sep 2026',initials:'SG',note:'This award would help me purchase materials for my final-year studio project.'},
            {id:'BUR-2026-0143',name:'Liam Chen',email:'liam.chen@campus.edu',course:'BSc Mathematics',year:'Year 2',type:'Access bursary',amount:2700,status:'Rejected',date:'10 Sep 2026',initials:'LC',note:'I am applying for support with accommodation and textbooks this academic year.'}
        ];
        const readStore=(key,fallback)=>{try{const item=localStorage.getItem(key);return item?JSON.parse(item):fallback}catch{return fallback}};
        let applications=readStore('scholarship-applications',initialApplications);
        const demoAccounts=[
            {name:'Amara Okafor',email:'amara.okafor@campus.edu',password:'Student123!',role:'student',admissionNumber:'STU-2024-00148',course:'BSc Environmental Science',year:'Year 2'},
            {name:'Avery Okafor',email:'officer@scholarship.edu',password:'Officer123!',role:'officer'},
            {name:'Jordan Ellis',email:'admin@scholarship.edu',password:'Admin123!',role:'admin'}
        ];
        let accounts=readStore('scholarship-accounts',demoAccounts);
        let currentUser=readStore('scholarship-session',null);
        let role=currentUser?.role||'student';
        let loginMode='student';
        let page='dashboard';let filter='All statuses';let search='';let toastTimer;
        const people={officer:{name:'Avery Okafor',initials:'AO',title:'Bursary officer'},student:{name:'Amara Okafor',initials:'AO',title:'Student'},admin:{name:'Jordan Ellis',initials:'JE',title:'Administrator'}};
        const bursaryOfficers=[
            {id:'avery',name:'Avery Okafor',role:'Bursary officer',email:'officer@scholarship.edu',phone:'+44 20 7946 0210'},
            {id:'maya',name:'Maya Patel',role:'Student funding officer',email:'maya.patel@scholarship.edu',phone:'+44 20 7946 0211'},
            {id:'daniel',name:'Daniel Reed',role:'Access bursary officer',email:'daniel.reed@scholarship.edu',phone:'+44 20 7946 0212'}
        ];
        const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
        const money=value=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(Number(value)||0);
        const save=()=>{try{localStorage.setItem('scholarship-applications',JSON.stringify(applications))}catch{showToast('Changes could not be saved in this browser')}};
        const navItems={officer:[['dashboard','⌂','Overview'],['applications','▤','Applications'],['students','♙','Students'],['programmes','◇','Bursary programmes']],student:[['dashboard','⌂','My dashboard'],['applications','▤','My applications'],['programmes','◇','Available bursaries']],admin:[['dashboard','⌂','Overview'],['applications','▤','All applications'],['students','♙','Students'],['programmes','◇','Programmes'],['reports','▥','Reports'],['settings','⚙','Settings']]};
        const titles={dashboard:'Dashboard',applications:role==='student'?'My applications':'Applications',students:'Students',programmes:'Bursary programmes',reports:'Reports',settings:'System settings'};
        function showToast(message){const toast=document.getElementById('toast');toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2600)}
        function renderOfficerContact(){const select=document.getElementById('officer-contact-select');const officer=bursaryOfficers.find(item=>item.id===select.value)||bursaryOfficers[0];document.getElementById('officer-contact-details').innerHTML=`<span>${esc(officer.role)}</span><a href="mailto:${esc(officer.email)}">${esc(officer.email)}</a><a href="tel:${esc(officer.phone.replace(/\s/g,''))}">${esc(officer.phone)}</a>`}
        function statusClass(status){return 'status-'+status.toLowerCase().replace(/\s+/g,'-')}
        function setPage(next){page=next;document.getElementById('sidebar').classList.remove('open');render()}
        function renderNav(){const nav=document.getElementById('navigation');nav.innerHTML=navItems[role].map(([key,icon,label])=>`<button class="${page===key?'active':''}" data-page="${key}"><span class="nav-icon">${icon}</span>${label}${key==='applications'&&role==='officer'?`<span class="nav-count">${applications.filter(a=>['Submitted','Under review'].includes(a.status)).length}</span>`:''}</button>`).join('');nav.querySelectorAll('[data-page]').forEach(button=>button.addEventListener('click',()=>setPage(button.dataset.page)))}
        function render(){
            if(!currentUser){showAuthView('login');return}
            role=currentUser.role;
            document.getElementById('auth-screen').classList.add('hidden');
            document.getElementById('app-shell').classList.remove('hidden');
            if(role==='student'&&!['dashboard','applications','programmes'].includes(page))page='dashboard';
            if(role==='officer'&&!['dashboard','applications','students','programmes'].includes(page))page='dashboard';
            if(role==='admin'&&!['dashboard','applications','students','programmes','reports','settings'].includes(page))page='dashboard';
            const initials=currentUser.name.split(/\s+/).map(part=>part[0]).join('').slice(0,2).toUpperCase();document.getElementById('side-name').textContent=currentUser.name;document.getElementById('side-role').textContent=role==='admin'?'System admin':role==='officer'?'Bursary officer':'Student';document.getElementById('side-avatar').textContent=initials;document.getElementById('top-avatar').textContent=initials;
            renderNav();document.getElementById('breadcrumb').textContent=`${role==='student'?'Student portal':role==='admin'?'Administration':'Bursary office'} / ${titles[page]||'Dashboard'}`;
            const content=document.getElementById('content');content.innerHTML=role==='student'?renderStudent():page==='dashboard'?renderDashboard():page==='applications'?renderApplications():page==='students'?renderStudents():page==='programmes'?renderProgrammes():page==='reports'?renderReports():renderSettings();bindContent();
        }
        function pageHead(kicker,title,subtitle,action=''){if(title==='Good morning, Avery'||title==='Good morning, Jordan')title=`Good morning, ${currentUser.name.split(/\s+/)[0]}`;return `<div class="page-head"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>`}
        function stat(label,value,note,icon){return `<div class="stat"><div class="stat-top"><span>${label}</span><span class="stat-icon">${icon}</span></div><div class="stat-value">${value}</div><div class="stat-note">${note}</div></div>`}
        function applicationTable(list,showStudent=true){
            const rows=list.map(a=>`<tr><td>${esc(a.id)}</td>${showStudent?`<td><div class="student-cell"><div class="mini-avatar">${esc(a.initials)}</div><div><strong>${esc(a.name)}</strong><small>${esc(a.course)}</small></div></div>`:''}<td>${esc(a.type)}</td><td class="amount">${money(a.amount)}</td><td><span class="pill ${statusClass(a.status)}">${esc(a.status)}</span></td><td>${esc(a.date)}</td><td><button class="row-action" data-open="${esc(a.id)}">${role==='student'?'View':'Review'} →</button></td></tr>`).join('');
            const columns=showStudent?'<th>Student</th>':'<th>Programme</th>';
            return `<div class="table-wrap"><table><thead><tr><th>Reference</th>${columns}<th>Bursary type</th><th>Amount</th><th>Status</th><th>Submitted</th><th></th></tr></thead><tbody>${rows||`<tr><td colspan="7"><div class="empty">No applications match your filters.</div></td></tr>`}</tbody></table></div>`
        }
        function filteredApplications(){let list=role==='student'?applications.filter(a=>a.email.toLowerCase()===currentUser.email.toLowerCase()):applications.slice();if(filter!=='All statuses')list=list.filter(a=>a.status===filter);if(search){const term=search.toLowerCase();list=list.filter(a=>[a.id,a.name,a.email,a.course,a.type].some(v=>String(v).toLowerCase().includes(term)))}return list}
        function filterControls(){return `<div class="filters"><div class="search"><input id="search-input" type="search" placeholder="Search by name or reference..." value="${esc(search)}" aria-label="Search applications"></div><select class="filter-select" id="status-filter" aria-label="Filter by status">${['All statuses','Submitted','Under review','Needs information','Approved','Rejected'].map(s=>`<option ${filter===s?'selected':''}>${s}</option>`).join('')}</select><select class="filter-select" id="type-filter" aria-label="Filter by bursary type"><option>All bursaries</option><option>Need-based bursary</option><option>Merit bursary</option><option>Access bursary</option></select></div>`}
        function renderDashboard(){
            const active=applications.filter(a=>['Submitted','Under review','Needs information'].includes(a.status)).length;const pending=applications.filter(a=>a.status==='Submitted').length;
            const kicker=role==='admin'?'ADMINISTRATION':role==='student'?'STUDENT PORTAL':'BURSARY OFFICE';const greeting=role==='admin'?'Good morning, Jordan':role==='student'?'Welcome back, Amara':'Good morning, Avery';
            const action=role==='student'?'<button class="btn btn-primary" data-action="new-application">＋ Start an application</button>':'';
            return `${pageHead(kicker,greeting,role==='student'?'Keep track of your funding applications and upcoming opportunities.':'Here is what is happening across your bursary programme this week.',action)}
                ${role==='student'?`<div class="welcome-strip"><div><strong>Your bursary journey, all in one place.</strong><p>Track decisions, check for updates, and discover support you may be eligible for.</p></div><span class="welcome-icon">✳</span></div>`:''}
                <div class="stats">${stat(role==='student'?'My applications':'Total applications',role==='student'?applications.filter(a=>a.email==='amara.okafor@campus.edu').length:applications.length,role==='student'?'Across all bursary programmes':'<strong>↑ 12%</strong> compared with last term','▤')}${stat(role==='student'?'In progress':'Awaiting review',role==='student'?applications.filter(a=>a.email==='amara.okafor@campus.edu'&&!['Approved','Rejected'].includes(a.status)).length:pending,'Applications needing attention','◷')}${stat(role==='student'?'Awarded to date':'Total awarded',role==='student'?money(applications.filter(a=>a.email==='amara.okafor@campus.edu'&&['Approved','Awarded','Paid'].includes(a.status)).reduce((sum,a)=>sum+Number(a.amount),0)):money(applications.filter(a=>['Approved','Awarded','Paid'].includes(a.status)).reduce((sum,a)=>sum+Number(a.amount),0)),role==='student'?'Your confirmed bursary support':'Across approved applications','◇')}${stat('Review completion',`${Math.round((applications.length-active)/Math.max(applications.length,1)*100)}%`,`${active} applications still active`,'✓')}</div>
                <div class="dashboard-grid"><section class="panel"><div class="panel-head"><div><div class="panel-title">${role==='student'?'Recent applications':'Application overview'}</div><div class="panel-subtitle">${role==='student'?'Your latest bursary applications':'Latest submissions across all bursaries'}</div></div><button class="text-link" data-page="applications">View all →</button></div>${applicationTable((role==='student'?applications.filter(a=>a.email==='amara.okafor@campus.edu'):applications).slice(0,4),role!=='student')}</section>
                <section class="panel"><div class="panel-head"><div><div class="panel-title">${role==='student'?'Coming up':'Key dates'}</div><div class="panel-subtitle">${role==='student'?'Keep these dates in mind':'Autumn 2026 application cycle'}</div></div></div><div class="deadline-list"><div class="deadline"><div class="date-box"><strong>30</strong>SEP</div><div><strong>Need-based bursary</strong><p>Application deadline · 5:00 pm</p></div></div><div class="deadline"><div class="date-box"><strong>12</strong>OCT</div><div><strong>Merit bursary decisions</strong><p>Decision notices sent by email</p></div></div><div class="deadline"><div class="date-box"><strong>21</strong>OCT</div><div><strong>Spring access fund</strong><p>Applications open</p></div></div></div></section></div>
                ${role==='admin'?`<section class="panel"><div class="panel-head"><div><div class="panel-title">Funding allocation</div><div class="panel-subtitle">Award distribution across active bursaries</div></div><button class="text-link" data-page="reports">View reports →</button></div>${[['Need-based bursary',68],['Merit bursary',47],['Access bursary',82]].map(([name,percent])=>`<div class="program-row"><div class="program-top"><span>${name}</span><span>${percent}% allocated</span></div><div class="progress-track"><div class="progress-fill" style="width:${percent}%"></div></div></div>`).join('')}</section>`:''}`
        }
        function renderApplications(){let list=filteredApplications();const title=role==='student'?'My applications':'Applications';const kicker=role==='admin'?'APPLICATIONS':'APPLICATION MANAGEMENT';return `${pageHead(kicker,title,role==='student'?'View your application status and bursary decisions.':'Search, filter, and review student funding requests.',role==='student'?'<button class="btn btn-primary" data-action="new-application">＋ Start an application</button>':'')}
            <section class="panel"><div class="panel-head"><div><div class="panel-title">${role==='student'?'Your submissions':`${applications.length} applications`}</div><div class="panel-subtitle">${role==='student'?'Status updates appear here as your application is reviewed.':'Autumn 2026 bursary cycle · Updated just now'}</div></div></div>${filterControls()}${applicationTable(list,role!=='student')}</section>`}
        function renderStudent(){if(page==='programmes')return renderProgrammes();if(page==='applications')return renderApplications();return renderStudentDashboard()}
        function renderStudentDashboard(){
            const ownApplications=applications.filter(application=>application.email.toLowerCase()===currentUser.email.toLowerCase());
            const active=ownApplications.filter(application=>!['Approved','Rejected'].includes(application.status)).length;
            const awarded=ownApplications.filter(application=>['Approved','Awarded','Paid'].includes(application.status)).reduce((total,application)=>total+Number(application.amount),0);
            const firstName=currentUser.name.split(/\s+/)[0];
            return `${pageHead('STUDENT PORTAL',`Welcome back, ${firstName}`,'Keep track of your funding applications and upcoming opportunities.','<button class="btn btn-primary" data-action="new-application">＋ Start an application</button>')}<div class="welcome-strip"><div><strong>Your bursary journey, all in one place.</strong><p>Track decisions, check for updates, and discover support you may be eligible for.</p></div><span class="welcome-icon">✳</span></div><div class="stats">${stat('My applications',ownApplications.length,'Across all bursary programmes','▤')}${stat('In progress',active,'Applications needing attention','◷')}${stat('Awarded to date',money(awarded),'Your confirmed bursary support','◇')}${stat('Upcoming deadline','30 Sep','Need-based bursary','✓')}</div><div class="dashboard-grid"><section class="panel"><div class="panel-head"><div><div class="panel-title">Recent applications</div><div class="panel-subtitle">Your latest bursary applications</div></div><button class="text-link" data-page="applications">View all →</button></div>${applicationTable(ownApplications.slice(0,4),false)}</section><section class="panel"><div class="panel-head"><div><div class="panel-title">Coming up</div><div class="panel-subtitle">Keep these dates in mind</div></div></div><div class="deadline-list"><div class="deadline"><div class="date-box"><strong>30</strong>SEP</div><div><strong>Need-based bursary</strong><p>Application deadline · 5:00 pm</p></div></div><div class="deadline"><div class="date-box"><strong>12</strong>OCT</div><div><strong>Merit bursary decisions</strong><p>Decision notices sent by email</p></div></div></div></section></div>`
        }
        function renderStudents(){const unique=[...new Map(applications.map(a=>[a.email,a])).values()];return `${pageHead('STUDENT DIRECTORY','Students','Students with bursary applications in the current cycle.')}<section class="panel"><div class="panel-head"><div><div class="panel-title">${unique.length} students</div><div class="panel-subtitle">Student contact and application overview</div></div><button class="btn btn-secondary btn-sm" data-action="export">↓ Export CSV</button></div><div class="table-wrap"><table><thead><tr><th>Student</th><th>Email</th><th>Course</th><th>Applications</th><th>Latest status</th></tr></thead><tbody>${unique.map(a=>`<tr><td><div class="student-cell"><div class="mini-avatar">${esc(a.initials)}</div><div><strong>${esc(a.name)}</strong><small>${esc(a.year)}</small></div></div></td><td>${esc(a.email)}</td><td>${esc(a.course)}</td><td>${applications.filter(item=>item.email===a.email).length}</td><td><span class="pill ${statusClass(a.status)}">${esc(a.status)}</span></td></tr>`).join('')}</tbody></table></div></section>`}
        function renderProgrammes(){const programs=[{name:'Need-based bursary',amount:'Up to £2,500',deadline:'30 September 2026',description:'Financial support for students facing unexpected hardship or limited household income.',eligibility:'Enrolled undergraduate students with demonstrated financial need.',open:true},{name:'Merit bursary',amount:'Up to £2,000',deadline:'12 October 2026',description:'Recognition for academic achievement, leadership, and contribution to the campus community.',eligibility:'Full-time students with a strong academic record.',open:true},{name:'Access bursary',amount:'Up to £3,500',deadline:'Spring term 2027',description:'Targeted funding that helps remove barriers to participation in higher education.',eligibility:'First-generation students and students with additional access needs.',open:false}];return `${pageHead('FUNDING OPPORTUNITIES','Bursary programmes','Explore funding available for the 2026–27 academic year.',role==='admin'?'<button class="btn btn-primary" data-action="new-programme">＋ Add programme</button>':'')}<div class="application-cards">${programs.map(p=>`<article class="panel" style="margin:0"><div class="panel-head"><div><div class="panel-title">${p.name}</div><div class="panel-subtitle">${p.open?'Applications open':'Coming soon'} · Deadline ${p.deadline}</div></div><span class="pill ${p.open?'status-approved':'status-submitted'}">${p.open?'Open':'Upcoming'}</span></div><div style="padding:0 18px 17px"><div class="amount" style="font-size:16px;margin-bottom:8px">${p.amount}</div><p style="color:#64726b;font-size:11px;margin:0 0 8px">${p.description}</p><div style="font-size:10px;color:#829088"><strong>Eligibility:</strong> ${p.eligibility}</div>${role==='student'&&p.open?'<button class="btn btn-primary btn-sm" style="margin-top:13px" data-action="new-application">Apply now →</button>':''}</div></article>`).join('')}</div>`}
        function renderReports(){const total=applications.length;const funded=applications.filter(a=>['Approved','Awarded','Paid'].includes(a.status));const awarded=funded.reduce((sum,a)=>sum+Number(a.amount),0);const byType=['Need-based bursary','Merit bursary','Access bursary'].map(type=>({type,count:applications.filter(a=>a.type===type).length}));return `${pageHead('INSIGHTS & REPORTING','Reports','A snapshot of application volume and current funding commitments.', '<button class="btn btn-secondary" data-action="export">↓ Export CSV</button>')}<div class="stats">${stat('Applications received',total,'Autumn 2026 cycle','▤')}${stat('Awards approved',funded.length,'Confirmed funding decisions','✓')}${stat('Funding committed',money(awarded),'Total approved amount','◇')}${stat('Average request',money(applications.reduce((sum,a)=>sum+Number(a.amount),0)/Math.max(total,1)),'Across all applications','◷')}</div><section class="panel"><div class="panel-head"><div><div class="panel-title">Applications by programme</div><div class="panel-subtitle">Current cycle submission totals</div></div></div>${byType.map(item=>`<div class="program-row"><div class="program-top"><span>${item.type}</span><span>${item.count} applications · ${total?Math.round(item.count/total*100):0}%</span></div><div class="progress-track"><div class="progress-fill" style="width:${total?item.count/total*100:0}%"></div></div></div>`).join('')}</section>`}
        function renderSettings(){return `${pageHead('ADMINISTRATION','System settings','Manage bursary portal preferences and review permissions.')}<div class="admin-grid"><section class="panel"><div class="panel-head"><div><div class="panel-title">Application cycle</div><div class="panel-subtitle">Current intake configuration</div></div></div><div style="padding:0 18px 12px"><div class="setting-row"><strong>Academic year</strong><span>2026–27</span></div><div class="setting-row"><strong>Cycle status</strong><span><span class="pill status-approved">Open</span></span></div><div class="setting-row"><strong>Applications received</strong><span>${applications.length}</span></div><div class="setting-row"><strong>Last updated</strong><span>2 October 2026</span></div></div></section><section class="panel"><div class="panel-head"><div><div class="panel-title">Review workflow</div><div class="panel-subtitle">Default application review settings</div></div></div><div style="padding:0 18px 12px"><div class="setting-row"><strong>Required reviewers</strong><span>1 officer</span></div><div class="setting-row"><strong>Decision notifications</strong><span>Enabled</span></div><div class="setting-row"><strong>Student status tracking</strong><span>Enabled</span></div><div class="setting-row"><strong>Data storage</strong><span>This browser (demo)</span></div></div></section></div><div class="notice">Demo mode: this portal stores sample application data in your browser only. It is not connected to a live student information system.</div>`}
        function bindContent(){document.querySelectorAll('[data-page]').forEach(button=>button.addEventListener('click',()=>setPage(button.dataset.page)));document.querySelectorAll('[data-open]').forEach(button=>button.addEventListener('click',()=>openReview(button.dataset.open)));document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',()=>runAction(button.dataset.action)));const searchInput=document.getElementById('search-input');if(searchInput){searchInput.addEventListener('input',()=>{search=searchInput.value;const position=searchInput.selectionStart;const list=filteredApplications();const table=document.querySelector('.table-wrap');if(table)table.outerHTML=applicationTable(list,role!=='student');bindRowActions()})}const statusFilter=document.getElementById('status-filter');if(statusFilter)statusFilter.addEventListener('change',()=>{filter=statusFilter.value;render()});const typeFilter=document.getElementById('type-filter');if(typeFilter)typeFilter.addEventListener('change',()=>{const type=typeFilter.value;const visible=filteredApplications().filter(a=>type==='All bursaries'||a.type===type);const table=document.querySelector('.table-wrap');if(table)table.outerHTML=applicationTable(visible,role!=='student');bindRowActions()})}
        function bindRowActions(){document.querySelectorAll('[data-open]').forEach(button=>button.addEventListener('click',()=>openReview(button.dataset.open)))}
        function runAction(action){if(action==='new-application'){openApplicationForm();if(role==='student'){document.getElementById('app-name').value=currentUser.name;document.getElementById('app-email').value=currentUser.email;document.getElementById('app-course').value=currentUser.course||'';document.getElementById('app-year').value=currentUser.year||'Year 1'}}if(action==='export')exportCsv();if(action==='new-programme')showToast('Programme creation is available in the live portal.')}
        function openModal(html){const backdrop=document.getElementById('modal-backdrop');document.getElementById('modal').innerHTML=html;backdrop.classList.add('open');backdrop.onclick=event=>{if(event.target===backdrop)closeModal()};document.getElementById('modal').querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',closeModal))}
        function closeModal(){document.getElementById('modal-backdrop').classList.remove('open')}
        function openApplicationForm(){openModal(`<div class="modal-head"><div><h2>Start an application</h2><p>Autumn 2026 bursary cycle · Fields marked required</p></div><button class="close-btn" data-close aria-label="Close">×</button></div><form class="modal-body" id="application-form"><div class="form-grid"><div class="field"><label for="app-name">Full name *</label><input id="app-name" name="name" value="${role==='student'?'Amara Okafor':''}" required></div><div class="field"><label for="app-email">Student email *</label><input id="app-email" name="email" type="email" value="${role==='student'?'amara.okafor@campus.edu':''}" required></div><div class="field"><label for="app-course">Course of study *</label><input id="app-course" name="course" value="${role==='student'?'BSc Environmental Science':''}" required></div><div class="field"><label for="app-year">Year of study *</label><select id="app-year" name="year"><option>Year 1</option><option selected>Year 2</option><option>Year 3</option><option>Year 4</option><option>Postgraduate</option></select></div><div class="field"><label for="app-type">Bursary programme *</label><select id="app-type" name="type"><option>Need-based bursary</option><option>Merit bursary</option><option>Access bursary</option></select></div><div class="field"><label for="app-amount">Amount requested (£) *</label><input id="app-amount" name="amount" type="number" min="100" max="5000" step="50" placeholder="e.g. 1500" required></div><div class="field full"><label for="app-note">Tell us how this bursary would support you *</label><textarea id="app-note" name="note" required placeholder="Briefly describe your circumstances and how the funding would help."></textarea><span class="form-help">Your response is only shared with the bursary review team.</span></div></div><div class="modal-actions"><button type="button" class="btn btn-secondary" data-close>Cancel</button><button class="btn btn-primary" type="submit">Submit application</button></div></form>`);document.getElementById('application-form').addEventListener('submit',event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target));const name=data.name.trim();applications.unshift({id:`BUR-2026-${String(149+applications.length-6).padStart(4,'0')}`,name,email:data.email.trim(),course:data.course.trim(),year:data.year,type:data.type,amount:Number(data.amount),status:'Submitted',date:new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date()),initials:name.split(/\s+/).map(part=>part[0]).join('').slice(0,2).toUpperCase(),note:data.note.trim()});save();closeModal();page='applications';render();showToast('Your application has been submitted.')})}
        openApplicationForm=function(){
            openModal(`<div class="modal-head"><div><h2>Start an application</h2><p>Autumn 2026 bursary cycle · Fields marked required</p></div><button class="close-btn" data-close aria-label="Close">×</button></div><form class="modal-body" id="application-form"><div class="form-grid"><div class="field"><label for="app-name">Full name *</label><input id="app-name" name="name" value="${role==='student'?esc(currentUser.name):''}" required></div><div class="field"><label for="app-email">Student email *</label><input id="app-email" name="email" type="email" value="${role==='student'?esc(currentUser.email):''}" required></div><div class="field"><label for="app-course">Course of study *</label><input id="app-course" name="course" value="${role==='student'?esc(currentUser.course||''):''}" required></div><div class="field"><label for="app-year">Year of study *</label><select id="app-year" name="year"><option>Year 1</option><option ${currentUser.year==='Year 2'?'selected':''}>Year 2</option><option>Year 3</option><option>Year 4</option><option>Postgraduate</option></select></div><div class="field"><label for="app-type">Bursary programme *</label><select id="app-type" name="type"><option>Need-based bursary</option><option>Merit bursary</option><option>Access bursary</option></select></div><div class="field"><label for="app-amount">Amount requested (£) *</label><input id="app-amount" name="amount" type="number" min="100" max="5000" step="50" placeholder="e.g. 1500" required></div><div class="field full"><label for="app-note">Tell us how this bursary would support you *</label><textarea id="app-note" name="note" required placeholder="Briefly describe your circumstances and how the funding would help."></textarea><span class="form-help">Your response is only shared with the bursary review team.</span></div><div class="field full transcript-field"><label for="app-transcript">Academic transcript (PDF) *</label><input id="app-transcript" name="transcript" type="file" accept=".pdf,application/pdf" required><span class="form-help">Upload a PDF up to 10 MB. The transcript will be attached to your application.</span></div></div><div class="modal-actions"><button type="button" class="btn btn-secondary" data-close>Cancel</button><button class="btn btn-primary" type="submit">Submit application</button></div></form>`);
            document.getElementById('application-form').addEventListener('submit',async event=>{
                event.preventDefault();
                const form=event.currentTarget;
                const file=document.getElementById('app-transcript').files[0];
                const helper=document.querySelector('.transcript-field .form-help');
                if(!file||!file.name.toLowerCase().endsWith('.pdf')){helper.textContent='Choose a PDF transcript to continue.';return}
                if(file.size>10*1024*1024){helper.textContent='The transcript must be 10 MB or smaller.';return}
                const data=Object.fromEntries(new FormData(form));
                const name=data.name.trim();
                const applicationId=`BUR-2026-${String(149+applications.length-6).padStart(4,'0')}`;
                const submitButton=form.querySelector('[type="submit"]');
                submitButton.disabled=true;
                submitButton.textContent='Uploading transcript…';
                try{
                    await storeTranscript(applicationId,file);
                    applications.unshift({id:applicationId,name,email:data.email.trim(),course:data.course.trim(),year:data.year,type:data.type,amount:Number(data.amount),status:'Submitted',date:new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date()),initials:name.split(/\s+/).map(part=>part[0]).join('').slice(0,2).toUpperCase(),note:data.note.trim(),transcript:{name:file.name,type:'application/pdf',size:file.size}});
                    save();closeModal();page='applications';render();showToast('Your application and transcript have been submitted.');
                }catch(error){submitButton.disabled=false;submitButton.textContent='Submit application';helper.textContent='The transcript could not be saved. Check browser storage and try again.'}
            });
        };
        function storeTranscript(applicationId,file){return new Promise((resolve,reject)=>{const request=indexedDB.open('scholarship-bursary-portal',2);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains('transcripts'))request.result.createObjectStore('transcripts')};request.onerror=()=>reject(request.error);request.onsuccess=()=>{const database=request.result;const transaction=database.transaction('transcripts','readwrite');transaction.objectStore('transcripts').put(file,applicationId);transaction.oncomplete=()=>{database.close();resolve()};transaction.onerror=()=>{database.close();reject(transaction.error)};transaction.onabort=()=>{database.close();reject(transaction.error)}}})}
        function readTranscript(applicationId){return new Promise((resolve,reject)=>{const request=indexedDB.open('scholarship-bursary-portal',2);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains('transcripts'))request.result.createObjectStore('transcripts')};request.onerror=()=>reject(request.error);request.onsuccess=()=>{const database=request.result;const transaction=database.transaction('transcripts','readonly');const getRequest=transaction.objectStore('transcripts').get(applicationId);getRequest.onsuccess=()=>{database.close();resolve(getRequest.result||null)};getRequest.onerror=()=>{database.close();reject(getRequest.error)}}})}
        async function downloadTranscript(application){try{const file=await readTranscript(application.id);if(!file){showToast('Transcript file is unavailable in this browser.');return}const url=URL.createObjectURL(file);const link=document.createElement('a');link.href=url;link.download=application.transcript?.name||'academic-transcript.pdf';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{showToast('Could not open the transcript file.')}}
        function openReview(id){
            const item=applications.find(application=>application.id===id);
            if(!item)return;
            const canReview=role!=='student';
            openModal(`<div class="modal-head"><div><h2>Application details</h2><p>${esc(item.id)} · Submitted ${esc(item.date)}</p></div><button class="close-btn" data-close aria-label="Close">×</button></div><div class="modal-body"><div class="detail-row"><span>Student</span><strong>${esc(item.name)} · ${esc(item.year)}</strong></div><div class="detail-row"><span>Email</span><strong>${esc(item.email)}</strong></div><div class="detail-row"><span>Course</span><strong>${esc(item.course)}</strong></div><div class="detail-row"><span>Bursary</span><strong>${esc(item.type)}</strong></div><div class="detail-row"><span>Amount requested</span><strong>${money(item.amount)}</strong></div><div class="detail-row"><span>Current status</span><strong><span class="pill ${statusClass(item.status)}">${esc(item.status)}</span></strong></div><div style="padding-top:15px"><div style="font-size:10px;font-weight:700;color:#52615a;margin-bottom:5px">STUDENT STATEMENT</div><div style="font-size:11px;line-height:1.7;color:#64726b">${esc(item.note||'No statement provided.')}</div></div>${canReview?`<div class="field" style="margin-top:16px"><label for="review-note">Review note</label><textarea id="review-note" placeholder="Optional note for the student..."></textarea></div><div class="modal-actions"><button class="btn btn-secondary" data-review="Needs information" data-id="${esc(item.id)}">Request information</button><button class="btn btn-danger" data-review="Rejected" data-id="${esc(item.id)}">Reject</button><button class="btn btn-primary" data-review="Approved" data-id="${esc(item.id)}">Approve</button></div>`:''}</div>`);
            document.querySelectorAll('[data-review]').forEach(button=>button.addEventListener('click',()=>{
                const target=applications.find(application=>application.id===button.dataset.id);
                if(target){target.status=button.dataset.review;save();closeModal();render();showToast(`Application ${target.status.toLowerCase()}.`)}
            }));
        }
        const openReviewWithoutTranscript=openReview;
        openReview=function(id){const application=applications.find(item=>item.id===id);openReviewWithoutTranscript(id);if(!application?.transcript)return;const row=document.createElement('div');row.className='detail-row transcript-file';const description=document.createElement('strong');description.textContent=`${application.transcript.name} · Academic transcript`;const button=document.createElement('button');button.type='button';button.className='row-action';button.textContent='Download';button.addEventListener('click',()=>downloadTranscript(application));row.append(description,button);const firstDetail=document.querySelector('#modal .detail-row');if(firstDetail)firstDetail.insertAdjacentElement('afterend',row)};
        function exportCsv(){const rows=[['Reference','Student','Email','Course','Bursary','Amount GBP','Status','Date'],...filteredApplications().map(a=>[a.id,a.name,a.email,a.course,a.type,a.amount,a.status,a.date])];const csv=rows.map(row=>row.map(value=>`"${String(value).replace(/"/g,'""')}"`).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='bursary-applications.csv';link.click();URL.revokeObjectURL(url);showToast('Application report exported.')}
        function showAuthView(view){document.getElementById('auth-screen').classList.remove('hidden');document.getElementById('app-shell').classList.add('hidden');document.querySelectorAll('.auth-form-view').forEach(panel=>panel.classList.toggle('hidden',panel.id!==`${view}-view`));document.querySelectorAll('.auth-tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.authView===view));document.querySelector('.login-mode-switch').classList.toggle('hidden',view!=='login');document.querySelectorAll('.auth-error').forEach(error=>error.textContent='');if(view==='login')setLoginMode(loginMode)}
        function setLoginMode(mode){loginMode=mode;document.querySelectorAll('.login-mode').forEach(panel=>panel.classList.toggle('hidden',panel.id!==`${mode}-login-view`));document.querySelectorAll('[data-login-mode]').forEach(button=>button.classList.toggle('active',button.dataset.loginMode===mode));document.querySelectorAll('.auth-error').forEach(error=>error.textContent='')}
        function startSession(account){const {password,...profile}=account;currentUser=profile;role=profile.role;page='dashboard';filter='All statuses';search='';localStorage.setItem('scholarship-session',JSON.stringify(currentUser));render()}
        document.querySelectorAll('[data-auth-view]').forEach(button=>button.addEventListener('click',()=>showAuthView(button.dataset.authView)));
        document.querySelectorAll('[data-login-mode]').forEach(button=>button.addEventListener('click',()=>setLoginMode(button.dataset.loginMode)));
        function signIn(event,allowedRoles,emailId,passwordId,errorId){event.preventDefault();const data=new FormData(event.currentTarget);const email=String(data.get('email')).trim().toLowerCase();const selectedRole=event.currentTarget.elements.role?.value;const account=accounts.find(item=>allowedRoles.includes(item.role)&&(!selectedRole||item.role===selectedRole)&&item.email.toLowerCase()===email&&item.password===data.get('password'));if(!account){document.getElementById(errorId).textContent='Email or password is incorrect for this sign-in.';return}startSession(account)}
        document.getElementById('student-login-form').addEventListener('submit',event=>signIn(event,['student'],'student-login-email','student-login-password','student-login-error'));
        document.getElementById('staff-login-form').addEventListener('submit',event=>signIn(event,['officer','admin'],'staff-login-email','staff-login-password','staff-login-error'));
        document.getElementById('register-form').addEventListener('submit',event=>{
            event.preventDefault();
            const data=new FormData(event.currentTarget);
            const email=String(data.get('email')).trim().toLowerCase();
            const admissionNumber=String(data.get('admissionNumber')||'').trim();
            const accountRole=data.get('role');
            const error=document.getElementById('register-error');
            if(accounts.some(account=>account.email.toLowerCase()===email)){error.textContent='An account with this email already exists.';return}
            if(accountRole==='student'&&!admissionNumber){error.textContent='Enter your student admission number.';return}
            if(accountRole==='student'&&accounts.some(account=>account.role==='student'&&account.admissionNumber?.toLowerCase()===admissionNumber.toLowerCase())){error.textContent='An account with this admission number already exists.';return}
            if(data.get('password')!==data.get('confirm')){error.textContent='The passwords do not match.';return}
            const account={name:String(data.get('name')).trim(),email,password:data.get('password'),role:accountRole,admissionNumber:accountRole==='student'?admissionNumber:'',course:String(data.get('course')||'').trim(),year:data.get('year')||''};
            accounts.push(account);
            try{localStorage.setItem('scholarship-accounts',JSON.stringify(accounts));startSession(account)}catch{accounts.pop();error.textContent='This browser could not save the account. Please try again.'}
        });
        document.getElementById('register-role').addEventListener('change',event=>{const isStudent=event.target.value==='student';['register-admission-number','register-course','register-year'].forEach(id=>{const field=document.getElementById(id);field.closest('.field').classList.toggle('hidden',!isStudent);field.required=isStudent})});
        document.querySelectorAll('[data-demo-role]').forEach(button=>button.addEventListener('click',()=>{const account=accounts.find(item=>item.role===button.dataset.demoRole);if(!account)return;showAuthView('login');setLoginMode(account.role==='student'?'student':'staff');if(account.role==='student'){document.getElementById('student-login-email').value=account.email;document.getElementById('student-login-password').value=account.password}else{document.getElementById('staff-role').value=account.role;document.getElementById('staff-login-email').value=account.email;document.getElementById('staff-login-password').value=account.password}}));
        document.getElementById('sign-out').addEventListener('click',()=>{currentUser=null;localStorage.removeItem('scholarship-session');document.querySelectorAll('.login-form').forEach(form=>form.reset());showAuthView('login');setLoginMode('student')});
        document.getElementById('officer-contact-select').addEventListener('change',renderOfficerContact);renderOfficerContact();document.getElementById('mobile-menu').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));document.getElementById('notification-button').addEventListener('click',()=>showToast(role==='student'?'You are all caught up.':'You have new applications to review.'));document.addEventListener('keydown',event=>{if(event.key==='Escape')closeModal()});showAuthView('login');document.getElementById('register-role').dispatchEvent(new Event('change'));render();
    })();
